extraction:
  cpp:
    after_prepare:
      - wget "https://github.com/ivmai/bdwgc/releases/download/v8.0.4/gc-8.0.4.tar.gz"
      - tar xf gc-8.0.4.tar.gz
      - mv gc-8.0.4 bdwgc
    configure:
      command:
        - cmake .
    index:
      build_command:
        - cmake --build .
