extraction:
  cpp:
    after_prepare:
      - wget "https://www.hboehm.info/gc/gc_source/gc-8.0.4.tar.gz"
      - tar xf gc-8.0.4.tar.gz
      - mv gc-8.0.4 bdwgc
    configure:
      command:
        - cmake -G "Unix Makefiles" .
    index:
      build_command:
        - cmake --build . --config Release
