language: c
compiler: gcc

install:
  - git clone https://github.com/linux-test-project/lcov.git
  - cd lcov; sudo make install; cd ..
  - gem install coveralls-lcov
  - lcov --version
  - gcc --version

before_script:
  - lcov --directory . --zerocounters

script:
  - wget "https://www.hboehm.info/gc/gc_source/gc-8.0.4.tar.gz"
  - tar xf gc-8.0.4.tar.gz
  - mv gc-8.0.4 bdwgc
  - cmake .
  - cmake --build .

after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'bdwgc/*' '/usr/*' --output-file coverage.info # filter out system and bdwgc code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info # uploads to coveralls
  - bash <(curl -s https://codecov.io/bash)
