/*
    module  : aritysym.c
    version : 1.3
    date    : 10/23/17
*/
#include "runtime.h"

typedef struct aritytab {
    Operator op;
    char *arity;
} aritytab;

char *aritysym(int op)
{
    static aritytab aritytab[] = {
	{ BOOLEAN_, "A" },
	{ CHAR_, "A" },
	{ INTEGER_, "A" },
	{ SET_, "A" },
	{ STRING_, "A" },
	{ LIST_, "A" },
	{ FLOAT_, "A" },
	{ FILE_, "A" },
	{ USR_, "?" },
	{ ANON_FUNCT_, "?" },
	{ SYMBOL_, "?" },
	{ DO_NOTHING, "A" },
	{ DO_FALSE, "A" },
	{ DO_TRUE, "A" },
	{ DO_MAXINT, "A" },
	{ DO_SETSIZE, "A" },
	{ DO_STACK, "A" },
	{ DO_SYMTABMAX, "A" },
	{ DO_SYMTABINDEX, "A" },
	{ DO_DUMP, "A" },
	{ DO_CONTS, "A" },
	{ DO_AUTOPUT, "A" },
	{ DO_UNDEFERROR, "A" },
	{ DO_UNDEFS, "A" },
	{ DO_ECHO, "A" },
	{ DO_CLOCK, "A" },
	{ DO_TIME, "A" },
	{ DO_RAND, "A" },
	{ DO_MEMORYMAX, "A" },
	{ DO_STDIN, "A" },
	{ DO_STDOUT, "A" },
	{ DO_STDERR, "A" },
	{ DO_ID, "" },
	{ DO_DUP, "A" },
	{ DO_OVER, "A" },
	{ DO_PICK, "DA" },
	{ DO_SWAP, "DDAA" },
	{ DO_ROLLUP, "DDDAAA" },
	{ DO_ROLLDOWN, "DDDAAA" },
	{ DO_ROTATE, "DDDAAA" },
	{ DO_POPD, "DDA" },
	{ DO_DUPD, "DDAAA" },
	{ DO_SWAPD, "DDDAAA" },
	{ DO_ROLLUPD, "DDDDAAAA" },
	{ DO_ROLLDOWND, "DDDDAAAA" },
	{ DO_ROTATED, "DDDDAAAA" },
	{ DO_POP, "D" },
	{ DO_CHOICE, "DDDA" },
	{ DO_OR, "DDA" },
	{ DO_XOR, "DDA" },
	{ DO_AND, "DDA" },
	{ DO_NOT, "DA" },
	{ DO_PLUS, "DDA" },
	{ DO_MINUS, "DDA" },
	{ DO_MUL, "DDA" },
	{ DO_DIVIDE, "DDA" },
	{ DO_REM, "DDA" },
	{ DO_DIV, "DDAA" },
	{ DO_SIGN, "DA" },
	{ DO_NEG, "DA" },
	{ DO_ORD, "DA" },
	{ DO_CHR, "DA" },
	{ DO_ABS, "DA" },
	{ DO_ACOS, "DA" },
	{ DO_ASIN, "DA" },
	{ DO_ATAN, "DA" },
	{ DO_ATAN2, "DDA" },
	{ DO_CEIL, "DA" },
	{ DO_COS, "DA" },
	{ DO_COSH, "DA" },
	{ DO_EXP, "DA" },
	{ DO_FLOOR, "DA" },
	{ DO_ROUND, "DA" },
	{ DO_FREXP, "DAA" },
	{ DO_LDEXP, "DDA" },
	{ DO_LOG, "DA" },
	{ DO_LOG10, "DA" },
	{ DO_MODF, "DAA" },
	{ DO_POW, "DDA" },
	{ DO_SIN, "DA" },
	{ DO_SINH, "DA" },
	{ DO_SQRT, "DA" },
	{ DO_TAN, "DA" },
	{ DO_TANH, "DA" },
	{ DO_TRUNC, "DA" },
	{ DO_LOCALTIME, "DA" },
	{ DO_GMTIME, "DA" },
	{ DO_MKTIME, "DA" },
	{ DO_STRFTIME, "DDA" },
	{ DO_STRTOL, "DDA" },
	{ DO_STRTOD, "DA" },
	{ DO_FORMAT, "DDDDA" },
	{ DO_FORMATF, "DDDDA" },
	{ DO_SRAND, "D" },
	{ DO_PRED, "DA" },
	{ DO_SUCC, "DA" },
	{ DO_MAX, "DDA" },
	{ DO_MIN, "DDA" },
	{ DO_FCLOSE, "D" },
	{ DO_FEOF, "A" },
	{ DO_FERROR, "A" },
	{ DO_FFLUSH, "" },
	{ DO_FGET, "A" },
	{ DO_FGETCH, "A" },
	{ DO_FGETS, "A" },
	{ DO_FOPEN, "DDA" },
	{ DO_FREAD, "DA" },
	{ DO_FWRITE, "D" },
	{ DO_FREMOVE, "DA" },
	{ DO_FRENAME, "DDA" },
	{ DO_FILETIME, "DA" },
	{ DO_FPUT, "D" },
	{ DO_FPUTCH, "D" },
	{ DO_FPUTCHARS, "D" },
	{ DO_FPUTSTRING, "D" },
	{ DO_FSEEK, "DDA" },
	{ DO_FTELL, "A" },
	{ DO_UNSTACK, "?" },
	{ DO_CONS, "DDA" },
	{ DO_SWONS, "DDA" },
	{ DO_FIRST, "DA" },
	{ DO_REST, "DA" },
	{ DO_COMPARE, "DDA" },
	{ DO_AT, "DDA" },
	{ DO_OF, "DDA" },
	{ DO_SIZE, "DA" },
	{ DO_OPCASE, "DDA" },
	{ DO_CASE, "DD?" },
	{ DO_UNCONS, "DAA" },
	{ DO_UNSWONS, "DAA" },
	{ DO_DROP, "DDA" },
	{ DO_TAKE, "DDA" },
	{ DO_CONCAT, "DDA" },
	{ DO_ENCONCAT, "DDDA" },
	{ DO_NAME, "DA" },
	{ DO_INTERN, "DA" },
	{ DO_BODY, "DA" },
	{ DO_NULL, "DA" },
	{ DO_SMALL, "DA" },
	{ DO_GEQL, "DDA" },
	{ DO_GREATER, "DDA" },
	{ DO_LEQL, "DDA" },
	{ DO_LESS, "DDA" },
	{ DO_NEQL, "DDA" },
	{ DO_EQL, "DDA" },
	{ DO_EQUAL, "DDA" },
	{ DO_HAS, "DDA" },
	{ DO_IN, "DDA" },
	{ DO_INDEX, "DDA" },
	{ DO_SAMETYPE, "DDA" },
	{ DO_CASTING, "DDA" },
	{ DO_INTEGER, "DA" },
	{ DO_CHAR, "DA" },
	{ DO_LOGICAL, "DA" },
	{ DO_SET, "DA" },
	{ DO_STRING, "DA" },
	{ DO_LIST, "DA" },
	{ DO_LEAF, "DA" },
	{ DO_USER, "DA" },
	{ DO_FLOAT, "DA" },
	{ DO_FILE, "DA" },
	{ DO_I, "DA" },		// XXX
	{ DO_X, "DDAA" },	// XXX
	{ DO_DIP, "D?" },
	{ DO_APP1, "D?" },
	{ DO_APP11, "DDDA" },
	{ DO_APP12, "DDDDAA" },
	{ DO_CONSTRUCT, "DD?" },
	{ DO_NULLARY, "DA" },
	{ DO_UNARY, "DDA" },
	{ DO_UNARY2, "DDDAA" },
	{ DO_UNARY3, "DDDDAAA" },
	{ DO_UNARY4, "DDDDDAAAA" },
	{ DO_APP2, "DDDAA" },
	{ DO_APP3, "DDDDAAA" },
	{ DO_APP4, "DDDDDAAAA" },
	{ DO_BINARY, "DDDA" },
	{ DO_TERNARY, "DDDDA" },
	{ DO_CLEAVE, "DDDAA" },
	{ DO_BRANCH, "DDD?" },
	{ DO_IFTE, "DDDA" },	// XXX
	{ DO_IFINTEGER, "DDD?" },
	{ DO_IFCHAR, "DDD?" },
	{ DO_IFLOGICAL, "DDD?" },
	{ DO_IFSET, "DDD?" },
	{ DO_IFSTRING, "DDD?" },
	{ DO_IFLIST, "DDD?" },
	{ DO_IFFLOAT, "DDD?" },
	{ DO_IFFILE, "DDD?" },
	{ DO_COND, "DA" },	// XXX
	{ DO_WHILE, "DDDA" },
	{ DO_LINREC, "DDDDA" },	// XXX
	{ DO_TAILREC, "DDD?" },
	{ DO_BINREC, "DDDD?" },
	{ DO_GENREC, "DDDD?" },
	{ DO_CONDNESTREC, "DDA" },	// XXX
	{ DO_CONDLINREC, "DDA" },	// XXX
	{ DO_STEP, "DD?" },
	{ DO_FOLD, "DDDA" },
	{ DO_MAP, "DDA" },	// XXX
	{ DO_TIMES, "DDA" },
	{ DO_INFRA, "DDA" },
	{ DO_PRIMREC, "DDDA" },
	{ DO_FILTER, "DDA" },
	{ DO_SPLIT, "DDAAA" },
	{ DO_SOME, "DDA" },
	{ DO_ALL, "DDA" },
	{ DO_TREESTEP, "DDDA" },
	{ DO_TREEREC, "DDDA" },
	{ DO_TREEGENREC, "DDDDA" },
	{ DO_HELP, "" },
	{ DO_HELP1, "" },
	{ DO_HELPDETAIL, "D" },
	{ DO_MANUAL, "" },
	{ DO_HTML_MANUAL, "" },
	{ DO_LATEX_MANUAL, "" },
	{ DO_MANUAL_LIST, "A" },
	{ DO_SETTRACEGC, "D" },
	{ DO_SETAUTOPUT, "D" },
	{ DO_SETUNDEFERROR, "D" },
	{ DO_SETECHO, "D" },
	{ DO_GC, "" },
	{ DO_SYSTEM, "D" },
	{ DO_GETENV, "DA" },
	{ DO_ARGV, "A" },
	{ DO_ARGC, "A" },
	{ DO_MEMORYINDEX, "A" },
	{ DO_GET, "A" },
	{ DO_GETCH, "A" },
	{ DO_PUT, "D" },
	{ DO_PUTCH, "D" },
	{ DO_PUTCHARS, "D" },
	{ DO_INCLUDE, "D" },
	{ DO_ABORT, "" },
	{ DO_QUIT, "" },
	{ 0, "" },
    };
    int i;

    for (i = 0; aritytab[i].op; i++)
	if (aritytab[i].op == op)
	    return aritytab[i].arity;
    return "?";
}
