/*
    module  : mktime.c
    version : 1.4
    date    : 09/11/23
*/
#ifndef MKTIME_C
#define MKTIME_C

#include "decode.h"

/**
OK 1720  mktime  :  DA	T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
void mktime_(pEnv env)
{
#ifndef COMPILER
    Node node;
    struct tm t;

    PARM(1, HELP);
    node = lst_pop(env->stck);
    decode(node, &t);
    node.u.num = mktime(&t);
    node.op = INTEGER_;
    lst_push(env->stck, node);
#endif
}
#endif
