/*
    module  : mktime.c
    version : 1.2
    date    : 05/06/16
*/
#include "interp.h"

/*
mktime  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
/* mktime.c */
PRIVATE void mktime_(void)
{
    struct tm t;

    ONEPARAM("mktime");
    LIST("mktime");
    decode_time(&t);
    if (OUTSIDE) {
	stk->u.num = mktime(&t);
	stk->op = INTEGER_;
    } else
	UNARY(INTEGER_NEWNODE, mktime(&t));
}
