/*
    module  : mktime.c
    version : 1.9
    date    : 03/28/20
*/
#ifndef MKTIME_C
#define MKTIME_C

PRIVATE void decode_time(struct tm *t)
{
    Node *p;

    memset(t, 0, sizeof(struct tm));
    p = stk->u.lis;
    POP(stk);
    if (p && p->op == INTEGER_) {
	t->tm_year = p->u.num - 1900;
	POP(p);
    }
    if (p && p->op == INTEGER_) {
	t->tm_mon = p->u.num - 1;
	POP(p);
    }
    if (p && p->op == INTEGER_) {
	t->tm_mday = p->u.num;
	POP(p);
    }
    if (p && p->op == INTEGER_) {
	t->tm_hour = p->u.num;
	POP(p);
    }
    if (p && p->op == INTEGER_) {
	t->tm_min = p->u.num;
	POP(p);
    }
    if (p && p->op == INTEGER_) {
	t->tm_sec = p->u.num;
	POP(p);
    }
    if (p && p->op == BOOLEAN_) {
	t->tm_isdst = p->u.num;
	POP(p);
    }
    if (p && p->op == INTEGER_) {
	t->tm_yday = p->u.num;
	POP(p);
    }
    if (p && p->op == INTEGER_) {
	t->tm_wday = p->u.num;
	POP(p);
    }
}

/**
mktime  :  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
PRIVATE void do_mktime(void)
{
    struct tm t;

#ifndef OLD_RUNTIME
    if (compiling && LIST_1)
	;
    else
	COMPILE;
#endif
    ONEPARAM("mktime");
    LIST("mktime");
    decode_time(&t);
    PUSH(INTEGER_, mktime(&t));
}
#endif
