/*
    module  : mktime.c
    version : 1.11
    date    : 06/20/22
*/
#ifndef MKTIME_C
#define MKTIME_C

#include "decode.h"

/**
mktime  :  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
PRIVATE void do_mktime(pEnv env)
{
    struct tm t;

    COMPILE;
    ONEPARAM("mktime");
    LIST("mktime");
    decode_time(env, &t);
    PUSH_NUM(INTEGER_, mktime(&t));
}
#endif
